### ISSUE TITLE
Memory Issue with calc_scale_ray() in HybridLens

### ISSUE THREAD

**Issue by subhamtesla** [singer-yang/DeepLens#52]
Hello Yang,

I ran into an OOM crash while working with 6_hybridlens_design.py and have a couple of questions:

1.	I noticed that geolens.calc_scale_ray(...) is commented out due to a “major functional warning” about ray sampling changes. Could you explain the reasoning behind deprecating this method and any plans to update or replace it for accurate scale estimation?
2.	After switching to geolens.calc_scale_pinhole(...), the code still crashes at:

# In deeplens/optics/ray.py
self.opl = self.opl + n * t
# triggered by:
ray = ray.prop_to(-10.0)

with an error “CUDA out of memory. Tried to allocate 745058.06 GiB.” What would be the recommended approach to avoid this huge memory spike when propagating rays for PSF simulation?

Thank you for your guidance!

**Comment by subhamtesla** [comment]
Hello, thanks so much for your quick response earlier.

I updated the code as per your suggestion, and I corrected the tensor shape mismatches at the following locations:

- new_opl = ray.opl + t in aperture.py (line 40)
- new_opl = ray.opl + n * t in base.py (line 84)
- new_opl = ray.opl + t in phase.py (line 129)

However, I'm still encountering a CUDA out-of-memory crash at:

    new_opl = ray.opl + phi * (ray.wvln * 1e-3) / (2 * torch.pi)  # line 149 in phase.py

Even after aligning all tensor shapes, this line continues to trigger the OOM error.

Thanks again for your support!

**Comment by singer-yang** [comment]
Hello,

It is the same bug introduced by the new data structure. I have fixed this, please have a look.

Thank you a lot for pointing out the bug.

Best,
Xinge

**Comment by subhamtesla** [comment]
Hi! thank you for helping correct earlier bugs 🙌
While using the `HybridLens.psf()` function in `6_hybrid_lens_design.py`, I encountered an error when specifying an off-axis point with a moderate lateral offset:

psf = lens.psf(points=[3.0, 0.0, -10000.0], ks=101, wvln=0.489)

This results in the following error:

File ~/DeepLens/deeplens/geolens.py:972, in GeoLens.psf_center(self, point, method)
    ...
    assert (ray.valid == 1).any(), "No sampled rays is valid."
AssertionError: No sampled rays is valid.

I suspect this might be related to the field of view (FoV), but the angle appears quite small and shouldn’t be considered extreme for most optical systems. Surprisingly, the simulation works fine for smaller offsets like `points=[0.2, 0.0, -10000.0]`.

**Comment by singer-yang** [comment]
Hello, 

The x, y coordinates of the input should be within [-1, 1]
